### ISSUE TITLE
Big white space on horizontal scroll in OSX Chrome 48.0.2564.109

### ISSUE THREAD

**Issue by vrunoa** [NodeTogether/nodetogether.org#10]
@ashleygwilliams I scroll the page horizontally and found a big white space at the right. I'm trying to debug and found why, if I found the problem i'll make a PR.
![screen shot 2016-02-12 at 10 43 25](https://cloud.githubusercontent.com/assets/329957/13008529/9fe7e51e-d175-11e5-94f8-589a91d0dc2f.png)

**Comment by ashleygwilliams** [comment]
this should be fixed by #8 i think! please open another issue if you still see weirdness!

**Comment by vrunoa** [comment]
@ashleygwilliams perfect. I was trying to fix the exact same things. Go with that PR.
