### ISSUE TITLE
London

### ISSUE THREAD

**Issue by iancrowther** [NodeTogether/nodetogether.org#11]
Hi @ashleygwilliams 

I run the London Node User Group & Nodechool London.

Happy to help you guys get this event kicked off with venues, mentors etc

**Comment by ashleygwilliams** [comment]
hi @iancrowther! that's amazing. thanks for reaching out.

the key things we need to set up are:
- event sponsor: provide a space with table/desks, whiteboard, good wifi for 4-6hrs, likely the evening before the event
- food sponsor:  snacks/meal depending on the time of the event
- mentors!

forms for all of these exist on http://www.nodetogether.org, but i'd be happy to jump on a call with you to talk it out. people<>people connections is always better IMO.

**Comment by iancrowther** [comment]
I'll email you and setup a call

**Comment by unindented** [comment]
Did this go anywhere? The page hasn't been updated in months, and it all looks pretty abandoned.

I had a few friends apply, and they are super bummed...

**Comment by iancrowther** [comment]
the event went ahead, hosted by @ashleygwilliams.  Sorry you missed out :-(

**Comment by unindented** [comment]
@iancrowther I did go. The page was updated and the emails sent out a couple of days after I opened the issue.
