### ISSUE TITLE
Add clarity about teaching format

### ISSUE THREAD

**Issue by madbernard** [NodeTogether/nodetogether.org#14]
When I clicked though from Twitter, using Chrome for Android, I couldn't tell what format the teaching would be in.  Clicking on the "sign up as a learner" form, it seems to be location focused, with the "we can't provide help with travel or accommodations", but how long would a person need to be in that place? What might the instructional hours be? Would it be near public transit? What would someone need to bring? Would it be free?

I'd suggest that you add a few words above the fold about format, and add a chose paragraphs in About with more details.

**Comment by ashleygwilliams** [comment]
the most recent pull should help! thanks for filing :)
