### ISSUE TITLE
NodeTogether Austin, TX, USA November 2016

### ISSUE THREAD

**Issue by cdnadmin** [NodeTogether/nodetogether.org#29]
Just referencing [this](https://github.com/nodejs/live.nodejs.org/issues/76#issuecomment-227185896) discussion and continuing here for relevancy.

**Comment by cdnadmin** [comment]
Hey, @patriciarealini sent you email re: 

> i have meeting on monday, 10/10, to solidify our food/coffee/water sponsor.  
> 
> also, our venue sponsor needs the answers to those quesitons I emailed ya.  

Thx in advance!

**Comment by patriciarealini** [comment]
i did not receive an email from you @cdnadmin at either my work or personal email.

**Comment by cdnadmin** [comment]
getting with you on twitter

not sure what's going on with email...i just test again from mine to an external email address, and it works fine...

either way, i put the questions for ya in twitter
