### ISSUE TITLE
Organizer Email Bouncing Back

### ISSUE THREAD

**Issue by cdnadmin** [NodeTogether/nodetogether.org#30]
Hi y'all, I have the venue reserved for the Monday, November 28, 2016, NodeTogether event, but Patricia's email keeps bouncing back!  It used to work.  (???)

At any rate, I need to know if there is someone else I should be working with for this!

Thx!

**Comment by bnb** [comment]
@patriciarealini Would that be your email?

**Comment by cdnadmin** [comment]
Hey, Tierney ( @bnb ) , was good meeting you at NodeSummit.  Yes, that is the right Patricia.  Been trying to re-touch base with her.  No boo or bah either way.  Will keep trying.  :-)

**Comment by bnb** [comment]
@cdnadmin I'll try to pass your attempt along to her, if possible. 👍

**Comment by patriciarealini** [comment]
oh no! thanks for the heads up, i'll look into my email and see what's up. 

@cdnadmin you can email me at my work email for the time being. patricia@bustle.com

**Comment by cdnadmin** [comment]
@patriciarealini will do asap

**Comment by cdnadmin** [comment]
@patriciarealini email sent.

**Comment by cdnadmin** [comment]
Incidentally, venue is about to drop us if I don't get back with them soon.  Not sure that we still need it?  But would be good/courteous if I can give them a yes or a no on this.  

Thx.

**Comment by bnb** [comment]
@cdnadmin I've dropped a line to the Organizers group. I've not been a part of the venue stuff, so I'm not sure and can't respond - hopefully someone will be able to get back to you shortly!

**Comment by patriciarealini** [comment]
@cdnadmin hey Monico, I emailed you yesterday. please let me know if you got it or not.

**Comment by patriciarealini** [comment]
@cdnadmin also i've tested the original email address i provided you with and there haven't been any problems otherwise. i noticed you are using a third party service and your emails are coming from `bounce.secureserver.net`, you might want to check into this and make sure it's working properly.
