### ISSUE TITLE
nodetogether is a little weird on the phone :O

### ISSUE THREAD

**Issue by lrlna** [NodeTogether/nodetogether.org#9]
hiiiii!! Thanks for being so awesome and putting this together <3

I've noticed it's a little wonky on phones: would you like me to do a PR to fix it? :dancers: :zap: 

I am at a 95% confidence interval it's @ media query on `.brought-to-you`, and `width` on containers :smile:

**Comment by lrlna** [comment]
as I was typing this @watilde fixed it I think :100:

**Comment by watilde** [comment]
:high-five: :smile_cat:

**Comment by ashleygwilliams** [comment]
hey! thanks to both of you! i'm hardly a frontend dev -- tis why i teach node! anyways please please any and all PRs are welcome! and i'll review yours soon @watilde, much appreciated :)

**Comment by ashleygwilliams** [comment]
fix by #8
